// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("DAL.Domain.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Image")
                        .HasMaxLength(256);

                    b.Property<DateTime>("Time");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.HasKey("Id");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "https://cdn.myanimelist.net/images/anime/12/76049.jpg",
                            Time = new DateTime(2019, 4, 10, 11, 3, 57, 656, DateTimeKind.Local).AddTicks(1176),
                            Title = "One Punch Man",
                            Url = "https://myanimelist.net/anime/30276/One_Punch_Man",
                            UserName = "catnib"
                        },
                        new
                        {
                            Id = 2,
                            Image = "https://cdn.myanimelist.net/images/anime/3/77176.jpg",
                            Time = new DateTime(2019, 4, 10, 11, 3, 57, 657, DateTimeKind.Local).AddTicks(5112),
                            Title = "Mobile Suit Gundam Thunderbolt",
                            Url = "https://myanimelist.net/anime/31973/Mobile_Suit_Gundam_Thunderbolt",
                            UserName = "siegrest"
                        },
                        new
                        {
                            Id = 3,
                            Image = "https://cdn.myanimelist.net/images/anime/1562/100460.jpg",
                            Time = new DateTime(2019, 4, 10, 11, 3, 57, 657, DateTimeKind.Local).AddTicks(5128),
                            Title = "Fairy Gone",
                            Url = "https://myanimelist.net/anime/39063/Fairy_Gone",
                            UserName = "rinnex"
                        });
                });

            modelBuilder.Entity("DAL.Domain.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(64);

                    b.Property<int>("MovieId");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "action",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "really cool",
                            MovieId = 1
                        },
                        new
                        {
                            Id = 3,
                            Content = "military",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 4,
                            Content = "michael bay",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 5,
                            Content = "average at best",
                            MovieId = 2
                        },
                        new
                        {
                            Id = 6,
                            Content = "eh",
                            MovieId = 3
                        });
                });

            modelBuilder.Entity("DAL.Domain.Vote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Ip");

                    b.Property<int>("MovieId");

                    b.Property<DateTime>("Time");

                    b.Property<short>("Value");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("DAL.Domain.Tag", b =>
                {
                    b.HasOne("DAL.Domain.Movie", "Movie")
                        .WithMany("Tags")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DAL.Domain.Vote", b =>
                {
                    b.HasOne("DAL.Domain.Movie", "Movie")
                        .WithMany()
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
